### ISSUE TITLE
Is it possible for you to share the source code for the dll?

### ISSUE THREAD

**Issue by CarpetHead** [NullTale/UnityClipboardImage#2]
basically as title - thanks!

**Comment by NullTale** [comment]
Unfortunately, no I lost the code, but I looked in the history of what I built it from.

I used this library https://github.com/dacap/clip
In particular I modified this example https://github.com/dacap/clip/blob/main/examples/show_image.cpp

I imported it using this article
https://stackoverflow.com/questions/43630063/passing-byte-array-from-c-unmanaged-dll-to-c-sharp-unity

I did not bother with all the possible formats of the image on the clipboard, used one.

I hope it helps!

**Comment by CarpetHead** [comment]
that's all useful, thanks!
