### ISSUE TITLE
Include clip license

### ISSUE THREAD

**Issue by dacap** [NullTale/UnityClipboardImage#3]
Just in case, as said in #2, you have to include the license of https://github.com/dacap/clip with your project, and users of your project must include the same license. E.g. if a Unity game uses your project, the game should show the license of clip in its credits.

**Comment by NullTale** [comment]
Done 👍
https://github.com/NullTale/UnityClipboardImage

**Comment by dacap** [comment]
Cannot wait for our future little D-Tale :baby_bottle: :baby:
